sudo: required
services:
  - docker

before_install:
  - docker build -t harupy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run harupy/react-test npm test -- --coverage

after_success:
  - docker build -t harupy/multi-client ./client
  - docker build -t harupy/multi-nginx ./nginx
  - docker build -t harupy/multi-server ./server
  - docker build -t harupy/multi-worker ./worker
  
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # take those images and pus them to docker hub
  - docker push harupy/multi-client
  - docker push harupy/multi-nginx
  - docker push harupy/multi-server
  - docker push harupy/multi-worker
